/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RUQ.gui;

import RUQ.modelo.Alimento;
import RUQ.modelo.FichaSensorial;
import RUQ.modelo.Funcionario;
import RUQ.modelo.Tipo;
import java.awt.Component;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Isaias
 */
public class FCadSensorial extends javax.swing.JFrame {
    String err = "";
    /**
     * Creates new form FCadSensorial
     */
    public FCadSensorial() {
        initComponents();
        err = "Sqlite.Driver.Error";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoRefeicao = new javax.swing.ButtonGroup();
        txHoraEntrega = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chkSabor = new javax.swing.JCheckBox();
        chkOdor = new javax.swing.JCheckBox();
        chkAparencia = new javax.swing.JCheckBox();
        chkConsistencia = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelTemperaturas = new javax.swing.JPanel();
        comboAlimento3 = new javax.swing.JComboBox();
        comboAlimento9 = new javax.swing.JComboBox();
        comboAlimento10 = new javax.swing.JComboBox();
        comboAlimento4 = new javax.swing.JComboBox();
        comboAlimento7 = new javax.swing.JComboBox();
        comboAlimento6 = new javax.swing.JComboBox();
        comboAlimento5 = new javax.swing.JComboBox();
        comboAlimento8 = new javax.swing.JComboBox();
        comboAlimento11 = new javax.swing.JComboBox();
        comboAlimento1 = new javax.swing.JComboBox();
        comboAlimento2 = new javax.swing.JComboBox();
        txOpcao2 = new javax.swing.JTextField();
        txOpcao1 = new javax.swing.JTextField();
        txAlimento2 = new javax.swing.JTextField();
        txAlimento1 = new javax.swing.JTextField();
        txAlimento3 = new javax.swing.JTextField();
        txAlimento4 = new javax.swing.JTextField();
        txAlimento5 = new javax.swing.JTextField();
        txAlimento6 = new javax.swing.JTextField();
        txAlimento9 = new javax.swing.JTextField();
        txAlimento8 = new javax.swing.JTextField();
        txAlimento7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txObservacoes = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jPnlImagemBack = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txHoraDistribuicao = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jrBtnAlmoco = new javax.swing.JRadioButton();
        jrBtnJantar = new javax.swing.JRadioButton();
        txNomeResponsavel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txDataEntrega = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        txDataDistribuicao = new javax.swing.JFormattedTextField();
        txTituloCardapio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Recebimento  v0.9.8");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txHoraEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txHoraEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHoraEntregaActionPerformed(evt);
            }
        });

        jLabel2.setText("Hora entrega:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)), "Análise Sensorial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N
        jPanel1.setToolTipText("");

        chkSabor.setText("Aprovado");

        chkOdor.setText("Aprovado");
        chkOdor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkOdorActionPerformed(evt);
            }
        });

        chkAparencia.setText("Aprovado");

        chkConsistencia.setText("Aprovado");

        jLabel1.setText("Sabor");

        jLabel4.setText("Odor");

        jLabel6.setText("Aparência:");

        jLabel7.setText("Consistência:");

        jPanelTemperaturas.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperaturas"));

        comboAlimento3.setPrototypeDisplayValue("XXXXXX");
        comboAlimento3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento3PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento9.setPrototypeDisplayValue("XXXXXXX");
        comboAlimento9.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento9PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento10.setPrototypeDisplayValue("XXXXXXX");
        comboAlimento10.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento10PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento4.setPrototypeDisplayValue("XXXXXX");
        comboAlimento4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento4PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento7.setPrototypeDisplayValue("XXXXXXX");
        comboAlimento7.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento7PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento6.setPrototypeDisplayValue("XXXXXXX");
        comboAlimento6.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento6PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento5.setPrototypeDisplayValue("XXXXXX");
        comboAlimento5.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento5PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento8.setPrototypeDisplayValue("XXXXXXX");
        comboAlimento8.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento8PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento11.setPrototypeDisplayValue("XXXXXXX");
        comboAlimento11.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento11PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento1.setPrototypeDisplayValue("XXXXXX");
        comboAlimento1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento1PopupMenuWillBecomeVisible(evt);
            }
        });

        comboAlimento2.setPrototypeDisplayValue("XXXXXX");
        comboAlimento2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                comboAlimento2PopupMenuWillBecomeVisible(evt);
            }
        });

        txAlimento3.setToolTipText("");

        txAlimento6.setToolTipText("");

        txAlimento8.setToolTipText("");

        javax.swing.GroupLayout jPanelTemperaturasLayout = new javax.swing.GroupLayout(jPanelTemperaturas);
        jPanelTemperaturas.setLayout(jPanelTemperaturasLayout);
        jPanelTemperaturasLayout.setHorizontalGroup(
            jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTemperaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboAlimento1, 0, 109, Short.MAX_VALUE)
                    .addComponent(comboAlimento2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAlimento4, 0, 73, Short.MAX_VALUE)
                    .addComponent(comboAlimento3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboAlimento5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txAlimento1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAlimento2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAlimento3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboAlimento7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboAlimento6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboAlimento8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txAlimento4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAlimento5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAlimento6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTemperaturasLayout.createSequentialGroup()
                        .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboAlimento10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboAlimento9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txAlimento8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlimento7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTemperaturasLayout.createSequentialGroup()
                        .addComponent(comboAlimento11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txAlimento9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelTemperaturasLayout.setVerticalGroup(
            jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTemperaturasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAlimento3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboAlimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTemperaturasLayout.createSequentialGroup()
                        .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAlimento6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlimento4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAlimento7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlimento5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlimento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAlimento4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAlimento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAlimento8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlimento6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlimento3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAlimento5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelTemperaturasLayout.createSequentialGroup()
                        .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAlimento9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlimento7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAlimento10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlimento8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelTemperaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboAlimento11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlimento9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txAlimento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações"));

        txObservacoes.setColumns(20);
        txObservacoes.setRows(5);
        jScrollPane12.setViewportView(txObservacoes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane12)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Obs - Preparações Quentes até 60ºC  por 4h - Preparações frias até 10ºC por 4h");

        javax.swing.GroupLayout jPnlImagemBackLayout = new javax.swing.GroupLayout(jPnlImagemBack);
        jPnlImagemBack.setLayout(jPnlImagemBackLayout);
        jPnlImagemBackLayout.setHorizontalGroup(
            jPnlImagemBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPnlImagemBackLayout.setVerticalGroup(
            jPnlImagemBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelTemperaturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkSabor)
                            .addComponent(chkOdor))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkConsistencia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkAparencia)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jPnlImagemBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkSabor)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(chkAparencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkOdor)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(chkConsistencia)))
                    .addComponent(jPnlImagemBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanelTemperaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel5.setText("Responsável:");

        txHoraDistribuicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        txHoraDistribuicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHoraDistribuicaoActionPerformed(evt);
            }
        });

        jLabel3.setText("Hr. Distrib:");

        grupoTipoRefeicao.add(jrBtnAlmoco);
        jrBtnAlmoco.setText("Almoço");

        grupoTipoRefeicao.add(jrBtnJantar);
        jrBtnJantar.setText("Jantar");

        jLabel8.setText("Data entrega:");

        txDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel9.setText("Data distribuição:");

        txDataDistribuicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txDataDistribuicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txDataDistribuicaoFocusGained(evt);
            }
        });

        jLabel10.setText("Cardápio.:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txTituloCardapio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(397, 397, 397))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jrBtnAlmoco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrBtnJantar)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txDataDistribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txHoraDistribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txNomeResponsavel)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txTituloCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txDataDistribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txHoraEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jrBtnAlmoco)
                        .addComponent(jrBtnJantar)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txHoraDistribuicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btSair))
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Cadastro de Análise Sensorial 0.9 Abr2015");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txHoraEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHoraEntregaActionPerformed
       
    }//GEN-LAST:event_txHoraEntregaActionPerformed

    private void txHoraDistribuicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHoraDistribuicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHoraDistribuicaoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:     
    }//GEN-LAST:event_formWindowOpened

    private void chkOdorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkOdorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkOdorActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        // Validar a ficha]
        //return;
        try{
            
        if(true)//(validarFicha())
        {
            //Cadastrar a ficha
            //INSERT INTO `TblFichaSensorial`(`CodigoFicha`,`DataCriacao`,`HoraCriacao`,`DataRecebimento`,`HoraRecebimento`,`TipoRefeicao`,`HoraDistribuicao`,`NomeResponsavel`,`SaborAprovado`,`OdorAprovado`,`AparenciaAprovado`,`ConsistenciaAprovado`,`Observacoes`) VALUES (1,NULL,NULL,'','',0,NULL,NULL,0,0,0,0,NULL);
            this.setCursor(Cursor.WAIT_CURSOR);       
                Funcionario fun = new Funcionario(txNomeResponsavel.getText());
                FichaSensorial fichaSen = new FichaSensorial();
                fichaSen.setCardapio(txTituloCardapio.getText());
                fichaSen.setDataEntrega(txDataEntrega.getText());
                fichaSen.setHoraDeEntrega(txHoraEntrega.getText());
                fichaSen.setDataDistribuicao(txDataDistribuicao.getText());
                fichaSen.setHoraDistribuicao(txHoraDistribuicao.getText());
                //Tipo refeicao
                
                if (jrBtnAlmoco.isSelected()) {
                    fichaSen.setTipo(Tipo.ALMOCO);
                }
                else{
                    fichaSen.setTipo(Tipo.JANTAR);
                }
                //
                //tem operador ternario nessa bosta?
                fichaSen.setResponsavel(fun);
                if(chkSabor.isSelected()){
                    fichaSen.setSaborAprovado(1);
                }
                else{
                    fichaSen.setSaborAprovado(0);
                }
                if(chkOdor.isSelected()){
                    fichaSen.setOdorAprovado(1);
                }
                else{
                    fichaSen.setOdorAprovado(0);
                }
                if(chkAparencia.isSelected()){
                    fichaSen.setAparenciaAprovada(1);
                }
                else{
                    fichaSen.setAparenciaAprovada(0);
                }
                if(chkConsistencia.isSelected()){
                    fichaSen.setConsistenciaAprovada(1);
                }
                else{
                    fichaSen.setConsistenciaAprovada(0);
                }
                fichaSen.setObservacao(txObservacoes.getText());
                //Preencher os alimentos - (algum lugar no meu coração, sei que posso transformar isso num loop :)
                Alimento al = null;
                ArrayList<Alimento> listaDeAlimentos = new ArrayList<>();
                if(comboAlimento1.getSelectedItem() != null && !(comboAlimento1.getSelectedItem().toString().equals(""))){
                    al = (Alimento) comboAlimento1.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txOpcao1.getText()));
                    listaDeAlimentos.add(al);
                }
                
                if(comboAlimento2.getSelectedItem() != null && !(comboAlimento2.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento2.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txOpcao2.getText()));
                    listaDeAlimentos.add(al);
                }
                if(comboAlimento3.getSelectedItem() != null && !(comboAlimento3.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento3.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txAlimento1.getText()));    
                    listaDeAlimentos.add(al);
                }
                
                if(comboAlimento4.getSelectedItem() != null && !(comboAlimento4.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento4.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txAlimento2.getText()));
                    listaDeAlimentos.add(al);
                }
                if(comboAlimento5.getSelectedItem() != null && !(comboAlimento5.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento5.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txAlimento3.getText()));
                    listaDeAlimentos.add(al);
                }
                
                if(comboAlimento6.getSelectedItem() != null && !(comboAlimento6.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento6.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txAlimento4.getText()));
                    listaDeAlimentos.add(al);
                }
                
                if(comboAlimento7.getSelectedItem() != null && !(comboAlimento7.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento7.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txAlimento5.getText()));
                    listaDeAlimentos.add(al);
                }
                
                if(comboAlimento8.getSelectedItem() != null && !(comboAlimento8.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento8.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txAlimento6.getText()));
                    listaDeAlimentos.add(al);
                }
                
                if(comboAlimento9.getSelectedItem() != null && !(comboAlimento9.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento9.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txAlimento7.getText()));
                    listaDeAlimentos.add(al);
                }
                
                if(comboAlimento10.getSelectedItem() != null && !(comboAlimento10.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento10.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txAlimento8.getText()));
                    listaDeAlimentos.add(al);
                }
                
                if(comboAlimento11.getSelectedItem() != null && !(comboAlimento11.getSelectedItem().toString().equals(""))){
                    al = (Alimento)  comboAlimento11.getSelectedItem();
                    al.setTemperatura(Double.parseDouble(txAlimento9.getText()));
                    listaDeAlimentos.add(al);
                }
                
                //
                fichaSen.setListaDeAlimentos(listaDeAlimentos);
                JOptionPane.showMessageDialog(this, cadastrarFichaSen(fichaSen));
                //Cadasrar alimentos
                JOptionPane.showMessageDialog(this, cadastrarAlimentosFicha(fichaSen));
                //Limpar a tela!
                
                //Cadastrar os alimentos//Transformar num loop para os controles.
                
            this.setCursor(Cursor.DEFAULT_CURSOR);
        }
        
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar ficha. " + e.getMessage());
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void comboAlimento1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento1PopupMenuWillBecomeVisible
        //Carregar alimentos do banco de dados
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento1.removeAllItems();
        listarAlimentosCombo(comboAlimento1);
        this.setCursor(Cursor.DEFAULT_CURSOR);
        zerarTemperaturas();
    }//GEN-LAST:event_comboAlimento1PopupMenuWillBecomeVisible

    private void comboAlimento2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento2PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento2.removeAllItems();
        listarAlimentosCombo(comboAlimento2);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento2PopupMenuWillBecomeVisible

    private void comboAlimento3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento3PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento3.removeAllItems();
        listarAlimentosCombo(comboAlimento3);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento3PopupMenuWillBecomeVisible

    private void comboAlimento4PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento4PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento4.removeAllItems();
        listarAlimentosCombo(comboAlimento4);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento4PopupMenuWillBecomeVisible

    private void comboAlimento5PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento5PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento5.removeAllItems();
        listarAlimentosCombo(comboAlimento5);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento5PopupMenuWillBecomeVisible

    private void comboAlimento6PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento6PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento6.removeAllItems();
        listarAlimentosCombo(comboAlimento6);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento6PopupMenuWillBecomeVisible

    private void comboAlimento7PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento7PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento7.removeAllItems();
        listarAlimentosCombo(comboAlimento7);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento7PopupMenuWillBecomeVisible

    private void comboAlimento8PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento8PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento8.removeAllItems();
        listarAlimentosCombo(comboAlimento8);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento8PopupMenuWillBecomeVisible

    private void comboAlimento9PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento9PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento9.removeAllItems();
        listarAlimentosCombo(comboAlimento9);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento9PopupMenuWillBecomeVisible

    private void comboAlimento10PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento10PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento10.removeAllItems();
        listarAlimentosCombo(comboAlimento10);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento10PopupMenuWillBecomeVisible

    private void comboAlimento11PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboAlimento11PopupMenuWillBecomeVisible
        // TODO add your handling code here:
        this.setCursor(Cursor.WAIT_CURSOR);
        comboAlimento11.removeAllItems();
        listarAlimentosCombo(comboAlimento11);
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_comboAlimento11PopupMenuWillBecomeVisible

    private void txDataDistribuicaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txDataDistribuicaoFocusGained
        // TODO add your handling code here:
        if (!txDataEntrega.getText().isEmpty()) {
            txDataDistribuicao.setText(txDataEntrega.getText());
        }
    }//GEN-LAST:event_txDataDistribuicaoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCadSensorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCadSensorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCadSensorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCadSensorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCadSensorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btSair;
    private javax.swing.JCheckBox chkAparencia;
    private javax.swing.JCheckBox chkConsistencia;
    private javax.swing.JCheckBox chkOdor;
    private javax.swing.JCheckBox chkSabor;
    private javax.swing.JComboBox comboAlimento1;
    private javax.swing.JComboBox comboAlimento10;
    private javax.swing.JComboBox comboAlimento11;
    private javax.swing.JComboBox comboAlimento2;
    private javax.swing.JComboBox comboAlimento3;
    private javax.swing.JComboBox comboAlimento4;
    private javax.swing.JComboBox comboAlimento5;
    private javax.swing.JComboBox comboAlimento6;
    private javax.swing.JComboBox comboAlimento7;
    private javax.swing.JComboBox comboAlimento8;
    private javax.swing.JComboBox comboAlimento9;
    private javax.swing.ButtonGroup grupoTipoRefeicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelTemperaturas;
    private javax.swing.JPanel jPnlImagemBack;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JRadioButton jrBtnAlmoco;
    private javax.swing.JRadioButton jrBtnJantar;
    private javax.swing.JTextField txAlimento1;
    private javax.swing.JTextField txAlimento2;
    private javax.swing.JTextField txAlimento3;
    private javax.swing.JTextField txAlimento4;
    private javax.swing.JTextField txAlimento5;
    private javax.swing.JTextField txAlimento6;
    private javax.swing.JTextField txAlimento7;
    private javax.swing.JTextField txAlimento8;
    private javax.swing.JTextField txAlimento9;
    private javax.swing.JFormattedTextField txDataDistribuicao;
    private javax.swing.JFormattedTextField txDataEntrega;
    private javax.swing.JFormattedTextField txHoraDistribuicao;
    private javax.swing.JFormattedTextField txHoraEntrega;
    private javax.swing.JTextField txNomeResponsavel;
    private javax.swing.JTextArea txObservacoes;
    private javax.swing.JTextField txOpcao1;
    private javax.swing.JTextField txOpcao2;
    private javax.swing.JTextField txTituloCardapio;
    // End of variables declaration//GEN-END:variables

    boolean validarFicha()
    {
        if(txHoraEntrega.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Digite a hora da entrega.");
            return false;
        }
        if (txHoraDistribuicao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Digite a hora da distribuição.");
            return false;
        }
        //if (grupoTipoRefeicao.) {
        //    
        //}
        if (txNomeResponsavel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Digite o nome do responsavel.");
            return false;
        }
        return true;
    }
    
    Connection c = null;
    Statement stmt = null;
    
    //TODO: ALGUMA ALMA CARIDOSA QUE ENTENDE O DRAMA DO DIA A DIA UNIVERSITARIO
    //POR AMOR A ALÁ, MOVA ESSES METODOS PARA O MODELO/ENTIDADE
    public String cadastrarFichaSen(FichaSensorial ficha) throws ClassNotFoundException, SQLException{
        try 
        {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = Calendar.getInstance();
            
            String dataCriacao = dateFormat.format(cal.getTime());
            dateFormat = new SimpleDateFormat("HH:mm:ss");
            String horaCricao = dateFormat.format(cal.getTime());
            
            //banco de dados
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:dzero.db");
            c.setAutoCommit(false); //desliga transacao automatica
            stmt = c.createStatement(); //prepara a query
            
            //Obs, os \" são para as aspas fazer parte da string
            String sql = "INSERT INTO TblFichaSensorial VALUES (@CodigoFicha,\""+ ficha.getCardapio() +"\",\"" + dataCriacao + "\",\"" + horaCricao + "\", \"" + ficha.getDataEntrega() + "\", \"" +ficha.getHoraDeEntrega() + "\", " + ficha.getTipo().getVal() + " , \"" + ficha.getHoraDistribuicao() + "\" ,\"" + ficha.getDataDistribuicao()+ "\", \"" + ficha.getResponsavel().getNome() + "\", " + ficha.getSaborAprovado() + " ," + ficha.getOdorAprovado() + "," + ficha.getAparenciaAprovada()+ ", " + ficha.getConsistenciaAprovada()+ " , '" + ficha.getObservacao() +"');";                              

            stmt.executeUpdate(sql);
            stmt.close();
            c.commit();
            c.close();
            return "Ficha Cadastrada!";
        } 
        catch (ClassNotFoundException | SQLException e) {
            throw e;
            //return "0 - ERRO AO CADASTRAR Ficha : " + e.toString();
        }
    }
    
    public String cadastrarAlimentosFicha(FichaSensorial ficha) throws ClassNotFoundException, SQLException{
        try 
        {
            
            //banco de dados
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:dzero.db");
            c.setAutoCommit(false); //desliga transacao automatica
            stmt = c.createStatement(); //prepara a query
            
            //PEGAR O ID DA FICHA INSERIDA!
            int idFicha,idAlimento;
            idFicha = ultimoIdFicha();
            //Obs, os \" são para as aspas fazer parte da string
            int alimentosInseridos = 0;
            ArrayList<Alimento> listaDeAlimentos = ficha.getListaDeAlimentos();
            for (Alimento al : listaDeAlimentos) {                              
                String sql = "INSERT INTO TblFichaSensorialAlimento VALUES ("+ idFicha + "," + al.getID() + "," + al.getTemperatura() + ");";
                stmt.executeUpdate(sql);
                alimentosInseridos++;
            }
            stmt.close();
            c.commit();
            c.close();
            return "Alimentos Adicionados!";
        } 
        catch (ClassNotFoundException | SQLException e) {
            throw e;
            //return "0 - ERRO AO CADASTRAR Ficha : " + e.toString();
        }
    }
    
    public int ultimoIdFicha(){
        //DefaultListModel modelListaAlimentos = new DefaultListModel();
        try 
        {
            //banco de dados
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:dzero.db");
            stmt = c.createStatement(); //prepara a query
            //Obs, os \" são para as aspas fazer parte da string
            String sql = "SELECT seq from sqlite_sequence where name=\"TblFichaSensorial\"";
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                return rs.getInt("seq");
            }
            
            
            stmt.close();
        } 
        catch (ClassNotFoundException | SQLException e) 
        {
                JOptionPane.showMessageDialog(this, "0 - ERRO AO LISTAR ALIMENTOS : " + e.toString());
        }
        return -1;
    }
    
    public void listarAlimentosCombo( JComboBox combo){
        //DefaultListModel modelListaAlimentos = new DefaultListModel();
        Alimento al = null;
        try 
        {
            //banco de dados
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:dzero.db");
            stmt = c.createStatement(); //prepara a query
            //Obs, os \" são para as aspas fazer parte da string
            String sql = "SELECT idAlimento,NomeAlimento FROM TblAlimento;";
            ResultSet rs = stmt.executeQuery(sql);
            
            while (rs.next()) 
            {
                al = new Alimento();
                al.setID(rs.getInt("idAlimento"));
                al.setNome(rs.getString("NomeAlimento"));
                //txAreaAlimento.setText(txAreaAlimento.getText() + al.getNome() + "\n");
                //modelListaAlimentos.addElement(rs.getString("NomeAlimento"));
                combo.addItem(al);//(rs.getString("NomeAlimento"));
            }
            
            stmt.close();
        } 
        catch (ClassNotFoundException | SQLException e) 
        {
                JOptionPane.showMessageDialog(this, "0 - ERRO AO LISTAR ALIMENTOS : " + e.toString());
        }

    }

    private void zerarTemperaturas() {
        for (Component cp : jPanelTemperaturas.getComponents()) {
            if(cp instanceof JTextField){
                ((JTextField)cp).setText("0");
            }  
        }
    }
}
