/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RUQ.gui;

/**
 *
 * @author Isaias
 */
public class FConfiguracaoSis extends javax.swing.JFrame {

    /**
     * Creates new form FConfiguracaoSis
     */
    public FConfiguracaoSis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlGuiasCfg1 = new javax.swing.JTabbedPane();
        jPnlAparencia = new javax.swing.JPanel();
        jrBtnMetal = new javax.swing.JRadioButton();
        jrBtnNimbus = new javax.swing.JRadioButton();
        jPnlAbout = new javax.swing.JPanel();
        btnAceitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurações - RUQ");

        jrBtnMetal.setText("Metal");

        jrBtnNimbus.setText("Nimbus");
        jrBtnNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrBtnNimbusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlAparenciaLayout = new javax.swing.GroupLayout(jPnlAparencia);
        jPnlAparencia.setLayout(jPnlAparenciaLayout);
        jPnlAparenciaLayout.setHorizontalGroup(
            jPnlAparenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAparenciaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jrBtnMetal)
                .addGap(18, 18, 18)
                .addComponent(jrBtnNimbus)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPnlAparenciaLayout.setVerticalGroup(
            jPnlAparenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAparenciaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPnlAparenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrBtnMetal)
                    .addComponent(jrBtnNimbus))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        pnlGuiasCfg1.addTab("Aparencia", new javax.swing.ImageIcon(getClass().getResource("/RUQ/img/pincel1.png")), jPnlAparencia); // NOI18N

        javax.swing.GroupLayout jPnlAboutLayout = new javax.swing.GroupLayout(jPnlAbout);
        jPnlAbout.setLayout(jPnlAboutLayout);
        jPnlAboutLayout.setHorizontalGroup(
            jPnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        jPnlAboutLayout.setVerticalGroup(
            jPnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        pnlGuiasCfg1.addTab("Sobre", new javax.swing.ImageIcon(getClass().getResource("/RUQ/img/interrogat1.png")), jPnlAbout); // NOI18N

        btnAceitar.setText("Aceitar");
        btnAceitar.setToolTipText("Aceitar mudanças e voltar ao menu anterior");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceitar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlGuiasCfg1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGuiasCfg1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceitar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrBtnNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrBtnNimbusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrBtnNimbusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FConfiguracaoSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FConfiguracaoSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FConfiguracaoSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FConfiguracaoSis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FConfiguracaoSis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlAbout;
    private javax.swing.JPanel jPnlAparencia;
    private javax.swing.JRadioButton jrBtnMetal;
    private javax.swing.JRadioButton jrBtnNimbus;
    private javax.swing.JTabbedPane pnlGuiasCfg1;
    // End of variables declaration//GEN-END:variables
}
